sudo: required
services:
  - docker

before_install:
  - docker build -t ivanzanolla/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ivanzanolla/react-test npm test

after_success:
  - docker build -t ivanzanolla/multi-nginx:latest  ./nginx
  - docker build -t ivanzanolla/multi-server:latest   ./server
  - docker build -t ivanzanolla/multi-worker:latest   ./worker
  - docker build -t ivanzanolla/multi-client:latest   ./client  
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push ivanzanolla/multi-nginx:latest 
  - docker push ivanzanolla/multi-server:latest 
  - docker push ivanzanolla/multi-worker:latest 
  - docker push ivanzanolla/multi-client:latest 
